---
title: "Clean source data"
author: "Richard Adejumola"
date: "2026-04-10"
output: 
  html_document:
    toc: true
    number_sections: true
    code_folding: show
---

# Import data sets
```{r}

brfss_data24 <- read_csv("../brfssdata/brfss24.csv")

```

# Filter dataset for relevant variables
```{r}
fp_data <- brfss_data24 %>% 
      select(
        id = SEQNO,                         metropolis = '_METSTAT',            marital = MARITAL, 
        state = '_STATE',                   sex = SEXVAR,                       
        bmi = "_BMI5",                      bmi_cat = "_BMI5CAT",               education = '_EDUCAG',
        employment = EMPLOY1,               sight = BLIND,                      age =  '_AGE80',
        age_grp = '_AGE_G',                 ethnicity = "_IMPRACE",             income2 = '_INCOMG1',
        income = INCOME3,                   weight_lb = WEIGHT2,                height_in = HEIGHT3,
        weighting = "_LLCPWT",              health_rating = GENHLTH,            physical_health = '_PHYS14D',
                            
        mental_health = '_MENT14D',         memory = DECIDE,                    walk = DIFFWALK, 
        deaf = DEAF,                        health_insurance = PRIMINS2,        exercise = EXERANY2,
        is_insured = '_HLTHPL2',            last_checkup = CHECKUP1, 
                        
        heart_attack = CVDINFR4,            coronary_hd = CVDCRHD4,             stroke = CVDSTRK3,                       asthma = ASTHMA3,                   ever_cancer = CHCOCNC1,             ever_copd = CHCCOPD3, 
        ever_depression = ADDEPEV3,         ever_ckd = CHCKDNY2,                age_had_dm = DIABAGE4,
        ever_arthritis = HAVARTH4,          ever_diabetes = DIABETE4,           dm_type = DIABTYPE,   
         
        smoke = SMOKE100,                   av_drinks_daily = AVEDRNK4,         insulin = INSULIN1,             
        checked_hba1c = CHKHEMO3,           dm_education = DIABEDU1,            dm_feet = FEETSORE,        
        )
```


# Apply listwise deletion
This data step filters for observations who have diabetes only. Persons who were not diagnosed with diabetes at the time of survey are excluded from downstream analysis. 
```{r}
fp_data <- fp_data %>% 
    mutate(
      ever_diabetes = case_when(
        ever_diabetes > 1 ~ NA_real_, #code as missing
        .default = ever_diabetes
      ))
      
fp_data_nomiss <- fp_data %>% drop_na('ever_diabetes' ) #delete missing if they don't have diabetes
fp_data_nomiss <- fp_data %>% drop_na('dm_type' ) #delete missing if we don't know their diabetes type (1 or 2)

```

# View summary of complete cases
```{r}
summary(fp_data_nomiss)
```

# Export the data
```{r}
write_csv(fp_data_nomiss, "/Users/richard/Library/CloudStorage/OneDrive-UniversityofSaskatchewan/CHEP898/finalpaper/data/brfss24_fpdata_nomiss.csv")
```


